### ISSUE TITLE
Endpoints not protected

### ISSUE THREAD

**Issue by darkGreyShadow** [springfox/springfox-oath2-demo#1]
Steps to reproduce:

1. Run Server
2. Call endpoint for instant by clicking "try it out"

It is not necessary to authorize first as control is being passed to controller body.
Curl gets direct to execution part (skips security restrictions)

**Comment by mojaiq** [comment]
The issue for which this demo project was uploaded #1913 , was related to the Swagger UI. The demo project is to show this issue. Securing the service endpoints is not implemented as it is not required for this issue.
